Add support for SM4-XTS/CTS/HCTR2 encryption
google/fscryptctl pull request #36
Opened 2022-12-14 08:52 UTC by uudiin

This was added in Linux v6.2-rc1.

2022-12-15 22:30 UTC, ebiggers requested changes
Why does the title of the pull request mention HCTR2?  This has nothing to do with HCTR2.

2022-12-15 22:30 UTC, ebiggers commented on test.py
> +    filenames encryption, so that is not tested."""
The second sentence of the above comment makes no sense.

2022-12-15 22:30 UTC, ebiggers commented on fscrypt_uapi.h
> +#define FSCRYPT_MODE_SM4_CTS			8
Please sync this file from upstream.  There was not the only change to it.

2022-12-15 22:30 UTC, ebiggers commented on test.py
> +    for padding in [4, 16, 32, None]:
Maybe leave out the non-default filename padding tests, for simplicity.  Non-default filenames padding is already tested with other modes.  Testing it again with SM4 adds very little value, IMO.

2022-12-19 02:59 UTC, uudiin commented
> Why does the title of the pull request mention HCTR2? This has nothing to do with HCTR2.

It's a pity that SM4 failed to enable HCTR2 mode, I have deleted the relevant description.

2022-12-20 08:01 UTC, merged